version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"

  db:
    image: "postgres"
    hostname: "pg"
    container_name: "pg"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
