"""second

Revision ID: 6b6b47dfd009
Revises: 
Create Date: 2022-09-20 19:06:47.676191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6b47dfd009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'currency', ['id'])
    op.create_unique_constraint(None, 'rating', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'rating', type_='unique')
    op.drop_constraint(None, 'currency', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
