"""second

Revision ID: 90642a2f54c3
Revises: 100526ff281d
Create Date: 2022-09-19 21:48:07.469150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90642a2f54c3'
down_revision = '100526ff281d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'currency', ['id'])
    op.create_unique_constraint(None, 'rating', ['id'])
    op.add_column('transactions', sa.Column('transaction_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'transaction_id')
    op.drop_constraint(None, 'rating', type_='unique')
    op.drop_constraint(None, 'currency', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
