"""empty message

Revision ID: 3a49a4ea52d4
Revises: 
Create Date: 2022-09-06 19:49:47.750093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a49a4ea52d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Balance', sa.REAL(), nullable=False),
    sa.Column('CurrencyName', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Currency',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CurrencyName', sa.String(length=15), nullable=False),
    sa.Column('Buy', sa.REAL(), nullable=False),
    sa.Column('Sale', sa.REAL(), nullable=False),
    sa.Column('AvailableQuantity', sa.REAL(), nullable=False),
    sa.Column('Date', sa.String(length=10), nullable=False),
    sa.Column('Test', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Rating',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('CurrencyName', sa.String(length=10), nullable=False),
    sa.Column('Rating', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=50), nullable=False),
    sa.Column('Date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Transactions',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('CurrencyFrom', sa.String(length=10), nullable=False),
    sa.Column('CurrencyTo', sa.String(length=10), nullable=False),
    sa.Column('AmountSpent', sa.REAL(), nullable=False),
    sa.Column('ReceivedAmount', sa.REAL(), nullable=False),
    sa.Column('Rate', sa.Integer(), nullable=False),
    sa.Column('Commission', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('User',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Login', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id'),
    sa.UniqueConstraint('Login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Transactions')
    op.drop_table('Rating')
    op.drop_table('Currency')
    op.drop_table('Account')
    # ### end Alembic commands ###
