"""empty message

Revision ID: e1cc4d0a4179
Revises: 
Create Date: 2022-08-31 15:29:24.706198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cc4d0a4179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Balance', sa.REAL(), nullable=True),
    sa.Column('CurrencyName', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Currency',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('CurrencyName', sa.String(length=15), nullable=True),
    sa.Column('Buy', sa.REAL(), nullable=True),
    sa.Column('Sale', sa.REAL(), nullable=True),
    sa.Column('AvailableQuantity', sa.REAL(), nullable=True),
    sa.Column('Date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Rating',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('CurrencyName', sa.String(length=10), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.Column('Comment', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('Transactions',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('CurrencyFrom', sa.String(length=10), nullable=True),
    sa.Column('CurrencyTo', sa.String(length=10), nullable=True),
    sa.Column('AmountSpent', sa.REAL(), nullable=True),
    sa.Column('ReceivedAmount', sa.REAL(), nullable=True),
    sa.Column('Rate', sa.Integer(), nullable=True),
    sa.Column('Commission', sa.Integer(), nullable=True),
    sa.Column('Date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('User',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('Login', sa.String(length=20), nullable=True),
    sa.Column('Password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id'),
    sa.UniqueConstraint('Login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Transactions')
    op.drop_table('Rating')
    op.drop_table('Currency')
    op.drop_table('Account')
    # ### end Alembic commands ###
